services:
  - type: web
    name: medicare-flask-app
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    build:
      pythonVersion: 3.9
    envVars:
      - key: FLASK_ENV
        value: production